# Generated by Django 2.0.5 on 2018-06-01 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180601_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryParameterProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ParameterProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('str', 'str'), ('int', 'int'), ('float', 'float'), ('dict', 'dict'), ('list', 'list')], default='str', max_length=20)),
                ('priority', models.IntegerField(default=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.CategoryParameterProduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Product')),
            ],
        ),
    ]
