# Generated by Django 2.0.5 on 2018-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_categoryparameterproduct_parameterproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategoryproduct',
            name='priority',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='imagesproduct',
            name='priority',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='parameterproduct',
            name='type',
            field=models.CharField(choices=[('str', 'str'), ('bool', 'bool'), ('int', 'int'), ('float', 'float'), ('dict', 'dict'), ('list', 'list')], default='str', max_length=20),
        ),
    ]
