# Generated by Django 2.0.5 on 2018-06-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180602_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='priority',
            field=models.IntegerField(default=1000),
        ),
    ]
