# Generated by Django 2.0.5 on 2018-07-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_categoryproduct_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='parameters',
        ),
    ]
